---
name: Actions Workflow
on: 
  push:
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:

      - name: Before Checkout
        id: location
        run: |
          pwd
          ls -lah

      - name: Echo env
        id: echo
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"

      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: After Checkout
        id: after
        run: |
          pwd
          ls -lah
